version: '3.3'

networks:
  internal:
    external: false

services:
  base:
    build: ./base
    image: mapcentia/gc2core:base
  ecw:
    build: ./ecw
    image: mapcentia/gc2core:ecw
    depends_on:
      - base
  gdal:
    build: ./gdal
    image: mapcentia/gc2core:gdal
    depends_on:
      - ecw
  mapserver:
    build: ./mapserver
    image: mapcentia/gc2core:mapserver
    depends_on:
      - gdal
  gc2core:
    build: ./stable
    image: mapcentia/gc2core
    depends_on:
      - mapserver
    privileged: true
    volumes:
      - ../../geocloud2:/var/www/geocloud2
    networks:
      - default
      - internal
    ports:
      - "8080:80"
    environment:
      - POSTGIS_HOST=postgis
      - POSTGIS_DB=postgres
      - POSTGIS_USER=gc2
      - POSTGIS_PORT=5432
      - POSTGIS_PW=1234
      - POSTGIS_PGBOUNCER=false
  redis:
    image: redis
    networks:
      - default
      - internal
    ports:
      - "6379:6379"
  postgis:
    build: ./postgis
    image: mapcentia/postgis
    volumes:
      - postgis_var_lib_postgresql:/var/lib/postgresql
    networks:
      - default
      - internal
    ports:
      - "5432:5432"
    environment:
      - GC2_USER=gc2
      - GC2_PASSWORD=1234

volumes:
  postgis_var_lib_postgresql:





